version: '3.8'

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    environment:
      - HOST=0.0.0.0  # Слушать на всех интерфейсах
      - PORT=54322
      - LANG=ru_RU.UTF-8
      # Дополнительные переменные:
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_ALLOWED_IPS=0.0.0.0/0, ::/0
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "0.0.0.0:54321:51820/udp"  # Явное указание binding на все интерфейсы
      - "0.0.0.0:54322:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    dns:  # Добавление DNS-серверов для лучшей работы
      - 1.1.1.1
      - 8.8.8.8

volumes:
  etc_wireguard:

networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
